services:
  db:
      image: postgres
      container_name: luna_rectask
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: hydroponics_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  